spring:
  application:
    name: skills-agent-example
  ai:
    dashscope:
      api-key: ${AI_DASHSCOPE_API_KEY}

server:
  port: 8080

logging:
    level:
      com.alibaba.cloud.ai.graph.agent.interceptor.skills: DEBUG
      com.alibaba.cloud.ai.graph.agent: INFO
